on:
  push:
    branches:
      - feat/espinoza/app-infrastructure
  pull_request:
    branches:
      - release

name: Deploy Merchant Dockerfiles

jobs:
  deploy:
    name: Deploy to Cluster
    runs-on: ubuntu-latest
    environment: workflow-env
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push user-service image
        uses: docker/build-push-action@v4
        with:
          context: apps/merchant-api/
          file: ./apps/merchant-api/UserService/Dockerfile
          push: true
          tags: merchantecommerce/user-service:v1.0.0

      - name: Build and push inventory-service image
        uses: docker/build-push-action@v4
        with:
          context: apps/merchant-api/
          file: ./apps/merchant-api/InventoryService/Dockerfile
          push: true
          tags: merchantecommerce/inventory-service:v1.0.0

      - name: Build and push payment-service image
        uses: docker/build-push-action@v4
        with:
          context: apps/merchant-api/
          file: ./apps/merchant-api/PaymentService/Dockerfile
          push: true
          tags: merchantecommerce/payment-service:v1.0.0

      - name: Build and push notification-service image
        uses: docker/build-push-action@v4
        with:
          context: apps/merchant-api/
          file: ./apps/merchant-api/NotificationService/Dockerfile
          push: true
          tags: merchantecommerce/notification-service:v1.0.0

      - name: Build and push api-gateway image
        uses: docker/build-push-action@v4
        with:
          context: apps/merchant-api/ApiGateway
          file: ./apps/merchant-api/ApiGateway/Dockerfile
          push: true
          tags: merchantecommerce/api-gateway:v1.0.0


      - name: Build and push merchant-web image
        uses: docker/build-push-action@v4
        with:
          context: apps/merchant-web
          file: ./apps/merchant-web/Dockerfile
          push: true
          tags: merchantecommerce/merchant-web:v1.0.0
          build-args: |
            NEXT_PUBLIC_FIREBASE_API_KEY: "${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}"
            NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}"
            NEXT_PUBLIC_FIREBASE_PROJECT_ID: "${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}"
            NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}"
            NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}"
            NEXT_PUBLIC_FIREBASE_APP_ID: "${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}"
            NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: "${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}"
            NEXT_PUBLIC_API_SERVER_SIDE_URL: "${{ secrets.NEXT_PUBLIC_API_SERVER_SIDE_URL }}"
            NEXT_PUBLIC_API_URL: "${{ secrets.NEXT_PUBLIC_API_URL }}"

